name: Qodana Code Quality
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
env:
  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --linter,jetbrains/qodana-jvm:2025.1
          post-pr-comment: false
        env:
          QODANA_TOKEN: ${{ env.QODANA_TOKEN }}
          QODANA_ENDPOINT: "https://qodana.cloud"
